import type { Metadata } from "next";
import { Geist, Geist_Mono, Fugaz_One, Roboto, Roboto_Condensed, Bebas_Neue } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto"
})


const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400","500","700"], 
  variable: "--font-roboto-condensed",
});


const fugazOne = Fugaz_One({
  weight: "400",
  variable: "--font-fugaz-one",
  subsets: ["latin"],
})

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fugazOne.variable} ${roboto.variable} ${robotoCondensed.variable} ${bebasNeue.variable} antialiased`}
        
      >
        {children}
      </body>
    </html>
  );
}
